// Date: 2016/04/06 19:25:59
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.kanomiya.mcmod.cradleofnoesis.client.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelStackedMaterial extends ModelBase
{
	//fields
	ModelRenderer m11;
	ModelRenderer m12;
	ModelRenderer m13;
	ModelRenderer m21;
	ModelRenderer m22;
	ModelRenderer m31;

	public ModelStackedMaterial()
	{
		textureWidth = 32;
		textureHeight = 32;

		m11 = new ModelRenderer(this, 0, 0);
		m11.addBox(0F, 0F, 0F, 12, 3, 3);
		m11.setRotationPoint(-6F, 0F, -5F);
		m11.setTextureSize(32, 32);
		m12 = new ModelRenderer(this, 0, 0);
		m12.addBox(0F, 0F, 0F, 12, 3, 3);
		m12.setRotationPoint(-6F, 0F, -1F);
		m12.setTextureSize(32, 32);
		m13 = new ModelRenderer(this, 0, 0);
		m13.addBox(0F, 0F, 0F, 12, 3, 3);
		m13.setRotationPoint(-6F, 0F, 3F);
		m13.setTextureSize(32, 32);
		m21 = new ModelRenderer(this, 0, 0);
		m21.addBox(0F, 0F, 0F, 12, 3, 3);
		m21.setRotationPoint(-6F, 3F, -3F);
		m21.setTextureSize(32, 32);
		m22 = new ModelRenderer(this, 0, 0);
		m22.addBox(0F, 0F, 0F, 12, 3, 3);
		m22.setRotationPoint(-6F, 3F, 1F);
		m22.setTextureSize(32, 32);
		m31 = new ModelRenderer(this, 0, 0);
		m31.addBox(0F, 0F, 0F, 12, 3, 3);
		m31.setRotationPoint(-6F, 6F, -1F);
		m31.setTextureSize(32, 32);
	}

	@Override
	public void render(Entity entityIn, float p_78088_2_, float p_78088_3_, float p_78088_4_, float p_78088_5_, float p_78088_6_, float scale)
	{
		setRotationAngles(p_78088_2_, p_78088_3_, p_78088_4_, p_78088_5_, p_78088_6_, scale, entityIn);
		doRender(scale);
	}

	public void doRender(float f)
	{
		m11.render(f);
		m12.render(f);
		m13.render(f);
		m21.render(f);
		m22.render(f);
		m31.render(f);
	}

}
